[package]
name = "rust-letterboxd-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
scraper = "0.23.1"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
actix-web = "4"
actix-cors = "0.7.1"
serde_json = "1.0.140"
